[package]
name = "treewalk"
version = "0.1.0"
edition = "2021"
authors = ["Payton Ward"]
description = "Common utilities for exploring a file tree"
description = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
